version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          TargetGroups:
            - name: "eventfinder-tg-blue"
            - name: "eventfinder-tg-green"
          ContainerName: "nginx"
          ContainerPort: 5000
        PlatformVersion: "LATEST"
