version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 5000
        PlatformVersion: "LATEST"
Hooks:
  - BeforeInstall: "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateBeforeInstall"
  - AfterInstall: "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateAfterInstall"
  - AfterAllowTestTraffic: "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateAfterTestTrafficStarts"
  - BeforeAllowTraffic: "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateBeforeAllowingProductionTraffic"
  - AfterAllowTraffic: "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateAfterAllowingProductionTraffic"