version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "REPLACED_AT_DEPLOYMENT"  # Will be replaced dynamically
        LoadBalancerInfo:
          ContainerName: "nginx"  # Ensure this matches your container name in ECS
          ContainerPort: 5000
        PlatformVersion: "LATEST"

Hooks:
  BeforeInstall:
    - "arn:aws:lambda:us-west-2:650251709711:function:LLambdaFunctionToValidateBeforeInstall"
  AfterInstall:
    - "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateAfterInstall"
  AfterAllowTestTraffic:
    - "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateAfterTestTrafficStarts"
  BeforeAllowTraffic:
    - "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateBeforeAllowingProductionTraffic"
  AfterAllowTraffic:
    - "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateAfterAllowingProductionTraffic"
