version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:650251709711:task-definition/eventfinder-definition:11"  # Replace with your task ARN
        LoadBalancerInfo:
          TargetGroups:
            - name: "eventfinder-tg-blue"  # Original (blue) target group
            - name: "eventfinder-tg-green" # New (green) target group
          ContainerName: "nginx"
          ContainerPort: 5000
        PlatformVersion: "LATEST"
Hooks:
  - BeforeInstall:
      - Location: "arn:aws:lambda:us-west-2:650251709711:function:LLambdaFunctionToValidateBeforeInstall"
  - AfterInstall:
      - Location: "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateAfterInstall"
  - AfterAllowTestTraffic:
      - Location: "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateAfterTestTrafficStarts"
  - BeforeAllowTraffic:
      - Location: "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateBeforeAllowingProductionTraffic"
  - AfterAllowTraffic:
      - Location: "arn:aws:lambda:us-west-2:650251709711:function:LambdaFunctionToValidateAfterAllowingProductionTraffic"